export const PlanetTypes = {
  GET_PLANETS: "GET_PLANETS",
  FETCH_PLANETS_START: "FETCH_PLANETS_START",
  FETCH_PLANETS_SUCCESS: "FETCH_PLANETS_SUCCESS",
  FETCH_PLANETS_FAIL: "FETCH_PLANETS_FAIL",
};

export default PlanetTypes;
