const CART_TYPES = {
  ADD_PLANET: "ADD_PLANET",
  REMOVE_PLANET: "REMOVE_PLANET",
  ADD_STARSHIP: "ADD_STARSHIP",
  REMOVE_STARSHIP: "REMOVE_STARSHIP",
  UPDATE_DEPARTURE_DATE: "UPDATE_DEPARTURE_DATE",
  UPDATE_PERSON: "UPDATE_PERSON",
  TOGGLE_CARTPOPUP: "TOGGLE_CARTPOPUP",
  REFRESH_CARTPOPUP_PLANET: "REFRESH_CARTPOPUP_PLANET",
  REFRESH_CARTPOPUP_STARSHIP: "REFRESH_CARTPOPUP_STARSHIP",
};

export default CART_TYPES;
