const SlideTypes = {
  GET_SLIDES: "GET_SLIDES",
  NEXT_SLIDE: "NEXT_SLIDE",
  PREVIOUS_SLIDE: "PREVIOUS_SLIDE",
  UPDATE_ACTIVE_SLIDE_INFO: "UPDATE_ACTIVE_SLIDE_INFO",
  TOGGLE_SLIDE_INFO: "TOGGLE_SLIDE_INFO",
};

export default SlideTypes;
