const pageTypes = {
  UPDATE_HIDE_BANER: "UPDATE_HIDE_BANER",
  NEXT_THUMBNAIL: "NEXT_THUMBNAIL",
  DEFAULT_THUMBNAIL: "DEFAULT_THUMBNAIL",
  TOGGLE_ISLOADING: "TOGGLE_ISLOADING",
};

export default pageTypes;
