const BOOKING_TYPES = {
  GET_BOOKING_START: "GET_BOOKING_START",
  GET_BOOKING_SUCCESS: "GET_BOOKING_SUCCESS",
  GET_BOOKING_FAIL: "GET_BOOKING_FAIL",
  CREATE_BOOKING_START: "CREATE_BOOKING_START",
  CREATE_BOOKING_SUCCESS: "CREATE_BOOKING_SUCCESS",
  CREATE_BOOKING_FAIL: "CREATE_BOOKING_FAIL",
  // ADD_NEW_BOOKING_TO_LIST_START: "ADD_NEW_BOOKING_TO_LIST_START",
  ADD_NEW_BOOKING_TO_LIST_SUCCESS: "ADD_NEW_BOOKING_TO_LIST_SUCCESS",
  ADD_NEW_BOOKING_TO_LIST_FAIL: "ADD_NEW_BOOKING_TO_LIST_FAIL",
  DELETE_BOOKING_START: "DELETE_BOOKING_START",
  DELETE_BOOKING_SUCCESS: "DELETE_BOOKING_SUCCESS",
  DELETE_BOOKING_FAIL: "DELETE_BOOKING_FAIL",
  CLEAR_ERROR: "CLEAR_ERROR",
};

export default BOOKING_TYPES;
