const BOOKING_TYPES = {
  GET_BOOKING_START: "GET_BOOKING_START",
  GET_BOOKING_SUCCESS: "GET_BOOKING_SUCCESS",
  GET_BOOKING_FAIL: "GET_BOOKING_FAIL",
  DELETE_BOOKING: "DELETE_BOOKING",
  CREATE_BOOKING_START: "CREATE_BOOKING_START",
  CREATE_BOOKING_SUCCESS: "CREATE_BOOKING_SUCCESS",
  CREATE_BOOKING_FAIL: "CREATE_BOOKING_FAIL",
};

export default BOOKING_TYPES;
