const Starship_Types = {
  GET_STARSHIPS: "GET_STARSHIPS",
  UPDATE_ACTIVE_STARSHIP: "UPDATE_ACTIVE_STARSHIP",
  FETCH_STARSHIPS_START: "FETCH_STARSHIPS_START",
  FETCH_STARSHIPS_SUCCESS: "FETCH_STARSHIPS_SUCCESS",
  FETCH_STARSHIPS_FAIL: "FETCH_STARSHIPS_FAIL",
};

export default Starship_Types;
