const UserTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
};

module.exports = UserTypes;
